[project]
name = "nmea-gps-emulator"
version = "0.1.0"
description = "GNSS Emulator for serial or network output"
dependencies = [
    "psutil>=5.8.0",
    "pyproj>=3.0.0",
    "pyserial>=3.5",
    "certifi>=2024.6.2",
]
readme = "README.md"
requires-python = ">= 3.8"
license = "MIT"

[project.scripts]
"nmea-gps-emulator" = "nmea_gps_emulator:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/nmea_gps_emulator"]
